### ISSUE TITLE
safe functions still throwing exception?

### ISSUE THREAD

**Issue by flaviogrossi** [KamilLelonek/yaml-elixir#27]
I'm using yaml-elixir 2.0.0 with yamerl 0.7.0, latest elixir and erlang, and both the plain and the `!` versions seem to throw an erlang exception:

```elixir
iex(1)> YamlElixir.read_from_string "*invalid"
** (throw) {:yamerl_exception, [{:yamerl_parsing_error, :error, 'No anchor corresponds to alias "invalid"', 1, 1, :no_matching_anchor, {:yamerl_alias, 1, 1, 'invalid'}, []}]}
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_errors.erl:59: :yamerl_errors.throw/1
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:4123: :yamerl_parser.do_emit_token/2
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:3963: :yamerl_parser.emit_tokens2/4
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:3652: :yamerl_parser.queue_token_check_doc/3
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:602: :yamerl_parser.end_stream/5
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_constr.erl:470: :yamerl_constr.string/2
    (yaml_elixir) lib/yaml_elixir.ex:51: YamlElixir.read_from_string!/2
    (yaml_elixir) lib/yaml_elixir.ex:57: YamlElixir.read_from_string/2
iex(1)> YamlElixir.read_from_string! "*invalid"
** (throw) {:yamerl_exception, [{:yamerl_parsing_error, :error, 'No anchor corresponds to alias "invalid"', 1, 1, :no_matching_anchor, {:yamerl_alias, 1, 1, 'invalid'}, []}]}
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_errors.erl:59: :yamerl_errors.throw/1
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:4123: :yamerl_parser.do_emit_token/2
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:3963: :yamerl_parser.emit_tokens2/4
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:3652: :yamerl_parser.queue_token_check_doc/3
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_parser.erl:602: :yamerl_parser.end_stream/5
    (yamerl) /home/flavio/src/holocom-stack/deps/yamerl/src/yamerl_constr.erl:470: :yamerl_constr.string/2
    (yaml_elixir) lib/yaml_elixir.ex:51: YamlElixir.read_from_string!/2
iex(6)>
```

**Comment by KamilLelonek** [comment]
Fixed in [`2.0.1`](https://hex.pm/packages/yaml_elixir/2.0.1).
